### ISSUE TITLE
zeds skin

### ISSUE THREAD

**Issue by ivanmagadan** [NSHoffman/N7ZedsMut#33]
The problem is this. Added zeds to scrn balance

Zeds=(Alias="CL",ZedClass="N7ZedsMut.N7_Clot")
Zeds=(Alias="BL",ZedClass="N7ZedsMut.N7_Bloat")
Zeds=(Alias="GF",ZedClass="N7ZedsMut.N7_Gorefast")
Zeds=(Alias="CR",ZedClass="N7ZedsMut.N7_Crawler")
Zeds=(Alias="ST",ZedClass="N7ZedsMut.N7_Stalker")
Zeds=(Alias="SI",ZedClass="N7ZedsMut.N7_Siren")
Zeds=(Alias="HU",ZedClass="N7ZedsMut.N7_Husk")
Zeds=(Alias="SC",ZedClass="N7ZedsMut.N7_Scrake")
Zeds=(Alias="FP",ZedClass="N7ZedsMut.N7_Fleshpound")
Zeds=(Alias="PAT",ZedClass="N7ZedsMut.N7_Boss")

Everything is fine, zeds appear, but with a standard skin... Is there a solution?

**Comment by NSHoffman** [comment]
Zeds classes you're using have vanilla skins, try using ones from `SAVAGE` collection
https://github.com/NSHoffman/N7ZedsMut/blob/dev/Classes/N7_MonstersCollection_SAVAGE.uc

**Comment by ivanmagadan** [comment]
Thank you very much for the tip. Everything worked out :)
